//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenkouCards
{
    using System;
    using System.Collections.Generic;
    
    public partial class attempts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public attempts()
        {
            this.responses = new HashSet<responses>();
        }
    
        public int id { get; set; }
        public int userId { get; set; }
        public int deckId { get; set; }
        public decimal score { get; set; }
        public System.DateTime attemptDate { get; set; }
    
        public virtual decks decks { get; set; }
        public virtual users users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<responses> responses { get; set; }
    }
}
