//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenkouCards
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SenkoucardsConfig : DbContext
    {
        public SenkoucardsConfig()
            : base("name=SenkoucardsConfig")
        {
            //this.Configuration.LazyLoadingEnabled = true;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attempts> attempts { get; set; }
        public virtual DbSet<cards> cards { get; set; }
        public virtual DbSet<cardsAudios> cardsAudios { get; set; }
        public virtual DbSet<cardsImages> cardsImages { get; set; }
        public virtual DbSet<decks> decks { get; set; }
        public virtual DbSet<responses> responses { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
